language: node_js
node_js: stable
cache:
  directories:
    - node_modules

before_deploy:
  - "npm run build"

deploy:
  provider: surge
  skip_cleanup: true
  project: ./public/
  domain: viniciusgularte.surge.sh
  on:
    branch: master
 
